### ISSUE TITLE
回答モデル(Answer)の生成とテーブル作成

### ISSUE THREAD

**Issue by norahito** [norahito/dive23#10]
Answerモデルの生成とテーブルを作成する。

- [ ] Answerモデルを生成する
- [ ] マイグレーションを実行しテーブルを作成する。

**Comment by choochoopiston** [comment]
リマインドです。
`rails g model Answer user:references question:references content:text photo:string posi_counts:integer nega_counts:integer`
・バリデーション
→content, user_id, question_id 空NG
・マイグレーションファイル
→posi_counts、nega_counts 初期値0

**Comment by norahito** [comment]
バリデーションは下記のissue#34に移しました。
https://github.com/norahito/dive23/issues/34
このissueではモデルとテーブルの生成のみを行います。
