### ISSUE TITLE
不要なコミットを避けるためignoreの設定を行う。

### ISSUE THREAD

**Issue by norahito** [norahito/dive23#3]
ignoreの初期設定を行う。

- [x] ドットenv(.env)
- [x] macのローカルファイル( .DS_Store, .localized)
- [ ] uploader関係(/public/uploads/* )

**Comment by lasershow** [comment]
何をignoreするのか、記述しましょう。

**Comment by norahito** [comment]
- [ ] ドットenv(.env)
- [ ] macのローカルファイル( .DS_Store, .localized)
- [ ] uploader関係( /public/uploads/* )
