### ISSUE TITLE
Bootstrapの導入

### ISSUE THREAD

**Issue by norahito** [norahito/dive23#8]
gem　'Bootstrap'を導入する

- [ ]  gemの導入( bootstrap-sass )
- [ ]  基本cssを自動生成

**Comment by lasershow** [comment]
bootstrapのgemは、複数あるので最初からどれを使用するか指定するのがベストですね！

**Comment by norahito** [comment]
ご指摘頂いた点を修正しました。

**Comment by mktktmr** [comment]
bootstrapのgem `bootstrap-sass` でもいいですか？
bootstrapカスタマイズする際、sass使うならこっちのほうが良いと思います。

**Comment by norahito** [comment]
僕はbootstrap-sass でも良いと思います。

**Comment by mktktmr** [comment]
ではbootstrap-sassしますね。
bootstrapの使い方自体は変わりませんので。
