### ISSUE TITLE
質問テーブルに関するCRUDのプロトタイプ作成

### ISSUE THREAD

**Issue by norahito** [norahito/dive23#9]
質問テーブルに関するCRUDのプロトタイプを完成する。

- [ ] questionsのコントローラーの生成
- [ ] questionのVIEWを生成
- [ ] questionテーブルにデータの登録、更新、削除（物理削除）、編集が出来る様にする。（論理削除は別issueにて対応）

**Comment by choochoopiston** [comment]
リマインドです。
・ルーティングの作成もする。
resources :questions
・コントローラーの設定
→質問の閲覧は、非ユーザーも可
→質問の投稿は、ユーザのみ可
→自分の質問のみ、編集・削除可

**Comment by norahito** [comment]
コントローラの権限設定はissue#61に分けました。
https://github.com/norahito/dive23/issues/61
